name: TSS Server Build and Release

on:
  push:
    tags:
      - 'v*.*.*' # Triggers on pushes to tags like v1.0.0, v1.0.1, etc.

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install build tools (e.g., GCC, Make)
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential

    - name: Build C project
      run: |
        ./build.bat

    - name: Create Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          server.exe
        draft: false
        prerelease: false
